name: FastAPI Docker CI with ngrok

on:
  workflow_dispatch:   # manual trigger
  push:
    branches:
      - main

jobs:
  docker-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Docker
        run: docker --version

      - name: Build Docker image
        run: docker build -t fastapi-docker .

      - name: Run FastAPI container
        run: docker run -d --name fastapi-container -p 8000:8000 fastapi-docker

      - name: Install ngrok
        run: sudo snap install ngrok

      - name: Start ngrok
        run: ngrok http 8000

      - name: Test FastAPI endpoint
        run: curl http://localhost:8000
