name: Docker Python CI

on:
  workflow_dispatch:   # Allows manual trigger
  push:
    branches:
      - main

jobs:
  docker-job:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Docker (runner already has Docker)
      - name: Check Docker
        run: docker --version

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t hello-docker .

      # 4️⃣ Run Docker container
      - name: Run Python inside Docker
        run: docker run --rm hello-docker
